CREATE TYPE "PaymentFrequency" AS ENUM ('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY');

CREATE TYPE "PaymentAllocationOrder" AS ENUM ('LATE_FEE_INTEREST_PRINCIPAL', 'INTEREST_PRINCIPAL_LATE_FEE', 'PRINCIPAL_INTEREST_LATE_FEE');

CREATE TYPE "RenewalPolicy" AS ENUM ('PAID_ONLY', 'ADMIN_OVERRIDE', 'ALLOW_BALANCE');

CREATE TYPE "CashboxOpeningMode" AS ENUM ('MANUAL', 'SCHEDULED');

ALTER TABLE "Company"
ADD COLUMN "defaultInterestRate" DECIMAL(5,4) NOT NULL DEFAULT 0.20,
ADD COLUMN "defaultTermDays" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN "paymentFrequency" "PaymentFrequency" NOT NULL DEFAULT 'DAILY',
ADD COLUMN "lateFeeRate" DECIMAL(5,4) NOT NULL DEFAULT 0,
ADD COLUMN "lateFeeGraceDays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "paymentAllocationOrder" "PaymentAllocationOrder" NOT NULL DEFAULT 'LATE_FEE_INTEREST_PRINCIPAL',
ADD COLUMN "renewalPolicy" "RenewalPolicy" NOT NULL DEFAULT 'PAID_ONLY',
ADD COLUMN "cashboxOpeningMode" "CashboxOpeningMode" NOT NULL DEFAULT 'MANUAL',
ADD COLUMN "cashboxAutoOpenTime" TEXT;

ALTER TABLE "Loan"
ADD COLUMN "paymentFrequency" "PaymentFrequency" NOT NULL DEFAULT 'DAILY';
